#cloud-config
users:
  - name: miroshnichenko
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']  
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpEVTvLfMVp0ZydLogg5s1D8WzKQaY2n0MqDsBNX2YkoaHP1vHs0Aqg5ICFaKXwVnc1ns6ntMO8hYYm8ShO6fw47MFYm6JtnK7YItJT+MAj8gPYId1HiEaE47e1NSF6a5IVglw6eTo+KLHEhl+YS+zew/UcNcOYLcBP3hWdtGQmjRygy6o9BXkwUlDQ6PgwZ4A+8gd3wEkHNlabqB/43rJsDzJzMGRcduEdQAZh4A6KwXs3S9BpidSaAwwoV2DyK95PZl2w6/UfvdHeSjUkzoe+EiMbiDGXGkekDsuHKpm6Npdok3rd3wW8YgYHYimuT1VuUYw2aONffA45xIN3/udpT58JAfV1F7NrAq4g3nu5eFR97bPM9xUXYeW7Wy4x8VyzKLWKZH4LjyWiWp9bGsaJXiEsY/tIbYNpA7ZVHZszk8ObPLODZ1IVfAUNKHNMtZ9vrrWp0anRIeq2zfOCvM8bGfKm0gUJ9j6TWslEmE7uK6uSQLv7lqts7Aj2hq3rG0= miroshnichenko@pc5

disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true

packages:
  - nginx

runcmd:
  - [ systemctl, nginx-reload ]
  - [ systemctl, enable, nginx.service ]
  - [ systemctl, start, --no-block, nginx.service ]
  - [ sh, -c, "echo $(hostname | cut -d '.' -f 1 ) >> /var/www/html/index.html" ]